config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "top#index"
  resources :users, only: %i[new create]
  resources :diaries
  resources :password_resets, only: %i[new create edit update]

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  get "oauths/oauth"
  get "oauths/callback"
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
end

app/views/shared/_before_login_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
  <div class="container px-4 px-lg-5">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png', class: 'rounded-circle logo-img' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item">
          <%= link_to "login", login_path, class: "nav-link px-lg-3 py-3 py-lg-4" %>
        </li>
        <li class="nav-item">
          <%= link_to "signin", new_user_path, class: "nav-link px-lg-3 py-3 py-lg-4" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="border-top mt-5">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="small text-center text-muted">
          <%= link_to "Contact", "https://forms.gle/4kwNg9XWSLv58QeFA", target: "_blank", rel: "noopener noreferrer", class: "mx-2" %>
          <%= link_to "Privacy Policy", page_path("privacy_policy"), class: "mx-2" %>
          <%= link_to "Terms Of Use", page_path("terms_of_use"), class: "mx-2" %>
        </div>
        <div class="small text-center text-muted">Copyright &copy; 2024 - Pictio Diary</div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
  <div class="container px-4 px-lg-5">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png', class: 'rounded-circle logo-img' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item">
          <%= link_to "My Diaries", diaries_path, class: "nav-link px-lg-3 py-3 py-lg-4 btn btn-beige" %>
        </li>
        <li class="nav-item">
        <%= link_to "new", new_diary_path, class: "nav-link px-lg-3 py-3 py-lg-4 btn btn-beige" %>
        </li>
        <li class="nav-item">
          <%= link_to "logout", logout_path, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'ログアウトしますか？' }, class: "nav-link px-lg-3 py-3 py-lg-4 btn btn-beige" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
<div class="container px-4 px-lg-5">
    <a class="navbar-brand" href="#">PictioDiary</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto py-4 py-lg-0">
            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">login</a></li>
            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">signin</a></li>
        </ul>
    </div>
</div>
</nav>