config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "top#index"
  resources :users, only: %i[new create]
  resources :diaries
  resources :password_resets, only: %i[new create edit update]

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  get "oauths/oauth"
  get "oauths/callback"
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to diaries_path, success: "ログインしました"
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<% content_for(:title, t(".title")) %>
<div class="text-center" style="padding:50px 0">
  <div class="logo">Login</div>
  <div class="login-form-1">
    <%= form_with url: login_path, local: true, class: 'text-left', id: 'register-form' do |form| %>
      <div class="login-form-main-message"></div>
      <div class="main-login-form">
        <div class="login-group">
          <div class="form-group">
            <%= form.label :email, class: 'sr-only' %>
            <%= form.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= form.label :password, class: 'sr-only' %>
            <%= form.password_field :password, class: 'form-control' %>
          </div>
        <%= form.submit 'Login', class: 'login-button' %>
        </div>
      </div>
      <%= link_to "Login with Line", auth_at_provider_path(provider: :line) %>
      <div class="etc-login-form">
        <%= link_to 'パスワードをお忘れの方はこちら', new_password_reset_path %>
      </div>
    <% end %>
  </div>
</div>